### PR TITLE
use FlatList

### PR DESCRIPTION
**Pull request by oomathias**

### CODE REVIEW

**Comment by Scrabouillmax** [comment]
@oomathias what is the context here? 
Is this related to https://birdie.atlassian.net/browse/DEL-2997 or blocking the RN upgrade?

**Comment by sroze** [comment]
It's all red but I massively 👍 if you manage to make the infinite scrolling collection working :)

**Comment by sroze** [comment]
> I think it's buggy because you need to scroll down and maintain it a bit to load more at the moment.
> How did you test your code, I don't see any dummy app to try on in this repo?

@oomathias The dummy app was the one you are trying it on 😉

**Review by sroze — APPROVED** [review]
It's pretty much a full rewrite of the `ScollableCollection`; given AFAIK we are the only one using it, happy to give it a 👍

**Review by TimRobinson1 — COMMENTED** [review]
@oomathias Is this PR still relevant? 🙂  I see it's blocked.

**Comment by oomathias** [comment]
It's live in the app 🙈 
Good push, I think we need to redo all scrolling list in the app because it's triggering warning.
I POCed something and we could still use galette without this package.
Basically the infinite loader is not built in react, so we don't really need to use this and would make my PR obsolete.

**Pull request merged**
